/* COUNT, GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */
SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*) AS "QUANTIDADE DE REG DA TAB CLIENTE"
FROM CLIENTE;

/* OPERADOR GROUP BY */
SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE; /* ERRO */

SELECT SEXO, COUNT(*) AS "QUANTIDADE" FROM CLIENTE 
GROUP BY SEXO; /* CORRETO */

/* PERFORMANCE EM OPERADORES LOGICOS */

/* 1 MILHAO DE REGISTROS

PARA CONTAR 
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE GROUP BY CIDADE;

CONDICAO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUACAO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';

--- COLOCAR QUEM TEM MAIS REGISTROS MELHORA A PERFORMANCE ---

SITUACAO - TRATANDO COM AND / OU
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE CIDADE = 'RIO DE JANEIRO' AND SEXO = 'F';

--- COLOCAR QUEM TEM MENOS REGISTROS MELHORA A PERFORMANCE ---

*/