/* FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL = NULL; /* ERRADO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NULL; /* CORRETO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE EMAIL IS NOT NULL;