/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE 
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE 
WHERE SEXO = 'F';

/* IGUALDADE TOTAL */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'SC';

/* UTILIZANDO O LIKE */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'SC';

/* CARACTER CORINGA */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE '%CENTRO%';
