/* PRIMEIRA FORMA NORMAL */

/* REGRAS

1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA.
[AZUL, AMARELO, VERDE] - ELEMENTOS DE UM MESMO TIPO

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA.
[RUA BAIRRO RUA CIDADE ESTADO] 

3 - TODA TABELA NECESSITA DE PELO MENSO UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO.
-- CHAVE PRIMÁRIA --
- CHAVE NATURAL (CPF)
- CHAVE ARTICICIAL  (SENHA)

*/

/* NOVAS TABELAS

TABELA TELEFONE
- IDTELEFONE
- TIPO
- NUMERO 

TABELA ENDERECO 
-IDENDERECO 
- ESTADO 
- CIDADE 
- BAIRRO
- RUA

TABELA CLIENTE
- IDCLIENTE
- NOME
- SEXO
- CPF
- EMAIL

*/