/* COMENDO SELECT */

/* HORA E DATA*/
SELECT NOW(); 

/* ALIAS */
SELECT 'FELIPE MAFRA' AS PROFESSOR;

/* DADOS DE TABELA */
SELECT NOME, SEXO, EMAIL FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */
SELECT * FROM CLIENTE;  