/* UTILIZANDO UPDATE */
SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM'; /* ERRADO - NAO FAÇA */

/* NUNCA UTILIZAR UPDATE SEM WHERE */

UPDATE CLIENTE SET EMAIL = 'JOAO@GMAIL.COM.COM'
WHERE NOME = 'JOAO';